#!/bin/bash
#set -x
set -e

install-packages puppet
puppet module --debug --verbose install maestrodev/rvm

# Install rvm
puppet apply --debug --verbose <<< "
class bootstrap {
    rvm_system_ruby {
      'ruby-1.9.3':
        ensure      => 'present',
        default_use => true,
        # Binary rubies are not being found, thus we build from source
        #build_opts  => ['--binary'];
    }

	rvm_gem {
	  'librarian-puppet':
	    name         => 'librarian-puppet',
	    ruby_version => 'ruby-1.9.3',
	    ensure       => latest,
	    require      => Rvm_system_ruby['ruby-1.9.3'];
	}

	rvm_gem {
	  'puppet':
	    name         => 'puppet',
	    ruby_version => 'ruby-1.9.3',
	    ensure       => latest,
	    require      => Rvm_system_ruby['ruby-1.9.3'];
	}
}

include rvm
include bootstrap

Class['bootstrap'] -> Class['rvm']
"
# Get rvm into our environment
. /usr/local/rvm/scripts/rvm

# Use the ruby we installed
rvm use 1.9.3

pushd /etc/mozpuppet/
    librarian-puppet update --verbose
popd
