#!/bin/bash

RVM_RC=/etc/profile.d/rvm.sh

source $RVM_RC

rvm list

set -x
puppet apply --verbose \
    --hiera_config /etc/mozpuppet/modules/mozpuppet/hiera.yaml \
    --modulepath /etc/mozpuppet/modules/ \
    $1
