#!/bin/bash
# Write our etc/rc.local into the image
# (Obviously not suitable for downloadable images).

set -x -e

[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

mkdir -p $TMP_HOOKS_PATH/rclocal/
cp $DIB_DATA_PATH/rc.local $TMP_HOOKS_PATH/rclocal/rc.local
