#!/bin/bash
# Write our etc/rc.local into the image
# (Obviously not suitable for downloadable images).

set -x -e

[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

mkdir -p $TMP_HOOKS_PATH/runpuppet/
cp $DIB_DATA_PATH/run-puppet $TMP_HOOKS_PATH/runpuppet/run-puppet
